# Site Settings
title                    : "Haochun Tang / Homepage"
description              : "Master's student at Jilin University working on trustworthy LLM systems, AI security, and data privacy."
repository               : "thcxiker/thcxiker.github.io"
google_scholar_stats_use_cdn : false

# Google Analytics
google_analytics_id      :

# SEO Related
google_site_verification :
bing_site_verification   :
baidu_site_verification  :

# Site Author
author:
  name             : "Haochun Tang 唐浩淳"
  pronouns         :
  avatar           : "/images/pickles.jpg"
  bio              : "M.S. Student, Software Engineering"
  location         : "Changchun / Guangzhou, China"
  employer         : "Jilin University; TAI Lab, HKUST(GZ)"
  uri              :
  email            : "tanghc24@mails.jlu.edu.cn"
  googlescholar    : "https://scholar.google.com/citations?user=WC7JmUoAAAAJ"
  github           : "thcxiker"
  arxiv            : "https://arxiv.org/search/?query=Haochun+Tang&searchtype=author"
  pubmed           :
  researchgate     :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         :
  dblp             :
  orcid            :
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Output
permalink: /:categories/:title/
timezone: Asia/Shanghai

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
